---
- name: Deploy gut web application
  hosts: servername

  vars_files:
    - ../environments/{{ env }}/vars/deploy_vault.yml
    - ../environments/{{ env }}/vars/vars.yml
    - ../environments/{{ env }}/vars/deploy_vars.yml

  vars_prompt:
    - name: git_tag
      prompt: 'Enter a tag to deploy'
      private: no

  vars:
    release_console_path: "{{ ansistrano_release_path.stdout }}/app/console"
    release_var_path: "{{ ansistrano_release_path.stdout }}/var"
    release_web_path: "{{ ansistrano_release_path.stdout }}/web"
    release_config_path: "{{ ansistrano_release_path.stdout }}/app/config"
    release_logs_path: "{{ ansistrano_release_path.stdout }}/app/logs"
    release_cache_path: "{{ ansistrano_release_path.stdout }}/app/cache"
    ansistrano_keep_releases: 3

    # Ansistrano vars
    ansistrano_deploy_to: "{{ project_deploy_dir }}" # Base path to deploy to.
    ansistrano_deploy_via: git # Method used to deliver the code to the server. Options are copy, rsync, git, svn, s3 or download
    ansistrano_git_repo: https://gitlab.com/ouchayan/project.git # Location of the git repository
    ansistrano_git_branch: "{{ git_tag }}" # What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    
    # Hooks: custom tasks if you need them
    ansistrano_after_update_code_tasks_file: "./hooks/after-update-code-tasks.yml"
    ansistrano_before_symlink_tasks_file: "./hooks/before-symlink.yml"
    ansistrano_after_symlink_tasks_file: "./hooks/after-symlink.yml"
    ansistrano_after_symlink_shared_tasks_file: "./hooks/after-symlink-shared.yml"

    ansistrano_shared_paths:
      - app/logs

  environment:
    SYMFONY_ENV: "{{ env }}"
    
  roles:
    - ansistrano.deploy

